apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compute:apiexport:kubernetes:upsyncer-permission-policy
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status"]
    verbs: ["*"]
