name: Daily Image Cleanup
on:
  # every day at 01:30am
  schedule:
    - cron: '30 1 * * *'
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@374e2028c8fb93b7219f3771cd405fab95d3dec4 # tag=v1.2.0
        with:
          older-than: 1 month
          owner: kcp-dev
          repository: kcp
          package: kcp-prs
          delete-tags: '^pr-\d+-[a-z0-9]+-[a-z0-9]+$'
          use-regex: true
          dry-run: true
